#!/bin/sh

AFL=${TAFL:-../TriforceAFL}
if [ ! -z "$AARCH64" ] ; then
    B=magenta/build-magenta-qemu-arm64
    Q="$AFL/qemu-system-aarch64 -machine virt -cpu cortex-a57"
else
    B=magenta/build-magenta-pc-x86-64
    Q="$AFL/qemu-system-x86_64 -machine q35 -cpu Haswell,+smap"
fi

getSym() {
    name=$1
    nm $B/magenta.elf |grep "T $name"|cut -d' ' -f1
}

# platform_panic_start happens right away, but no messages printed
CRASH=`getSym platform_panic_start`

# run fuzzer and qemu-system
export AFL_SKIP_CRASHES=1
$AFL/afl-cmin -m 5000 -t 2000 -i mindir1 -o mindir2 -QQ -- $Q \
    -m 1024 -nographic -net none \
    -kernel $B/magenta.elf -initrd $B/bootdata.bin \
    -append "TERM=xterm-256color kernel.entropy=562afa809d13833970ecb91af535b7f35d0adaadb6d0afc681a2366ab2d376b4 kernel.halt_on_panic=true magenta.autorun.boot=/boot/bin/fuzz" \
    -aflPanicAddr "$CRASH" \
    -aflFile @@

