#!/bin/sh
#
# Boot the system to a shell in qemu, allowing gdb to connect.
#

AFL=${TAFL:-../TriforceAFL}
B=magenta/build-magenta-pc-x86-64

$AFL/afl-qemu-system-trace -s \
    -m 1024 -nographic -net none -machine q35 -cpu Haswell,+smap \
    -kernel $B/magenta.bin -initrd $B/bootdata.bin \
    -append "TERM=xterm-256color kernel.entropy=562afa809d13833970ecb91af535b7f35d0adaadb6d0afc681a2366ab2d376b4 kernel.halt_on_panic=true" \
    "$@"

