#!/bin/sh
#
# Run a series of test cases through the driver one at a time
# using the testAfl tool.
# If AARCH64 is set, run the AARCH64 kernel.
#

AFL=${TAFL:-../TriforceAFL}
if [ ! -z "$AARCH64" ] ; then
    B=magenta/build-magenta-qemu-arm64
    Q="$AFL/qemu-system-aarch64 -machine virt -cpu cortex-a57"
else
    B=magenta/build-magenta-pc-x86-64
    Q="$AFL/qemu-system-x86_64 -machine q35 -cpu Haswell,+smap"
fi

getSym() {
    name=$1
    nm $B/magenta.elf |grep "T $name"|cut -d' ' -f1
}

# panic_shell_start is called after printing the panic message
CRASH=`getSym panic_shell_start`

# platform_panic_start happens right away, but no messages printed
#CRASH=`getSym platform_panic_start`

./testAfl $Q \
    -m 1024 -nographic -net none \
    -kernel $B/magenta.elf -initrd $B/bootdata.bin \
    -append "TERM=xterm-256color kernel.entropy=562afa809d13833970ecb91af535b7f35d0adaadb6d0afc681a2366ab2d376b4 kernel.halt_on_panic=true fuzz=true" \
    -aflPanicAddr "$CRASH" \
    -aflFile @@ -- "$@"

